version: '3'
services:
  web:
    build:
      context: .
      target: metadata-image
    ports:
      - "8000:5065"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: 'postgres:12-alpine'
    ports:
      - 5500:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./migrations/scripts/create_metadata_db.sql:/docker-entrypoint-initdb.d/01.sql
      - ./migrations/scripts/create_metadata_schema.sql:/docker-entrypoint-initdb.d/02.sql
      - ./migrations/scripts/install_ltree.sql:/docker-entrypoint-initdb.d/03.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - "8750:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    logging:
      driver: none
    volumes:
      - ./local_config/pgadmin/:/var/lib/pgadmin/
    depends_on:
      db:
        condition: service_healthy

  alembic:
    build:
      context: .
      target: alembic-image
    depends_on:
      db:
        condition: service_healthy

networks:
  default:
    external:
      name: pilot-network
