version: '3'
services:
  web:
    build:
      context: .
      args:
        PIP_USERNAME: "${PIP_USERNAME}"
        PIP_PASSWORD: "${PIP_PASSWORD}"
    ports:
      - "8000:8000"
    environment:
      OPSDB_UTILILT_USERNAME: postgres
      OPSDB_UTILILT_PASSWORD: postgres
      OPSDB_UTILILT_HOST: db
      OPSDB_UTILILT_PORT: 5432
      OPSDB_UTILILT_NAME: metadata
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/metadata
    volumes:
    - .:/usr/src/app
    depends_on:
      - db
    command:
      sh -c "
        pip install alembic

        alembic upgrade head

        uvicorn app.main:app --reload --host 0.0.0.0
      "

  db:
    image: 'postgres:12-alpine'
    ports:
      - 5500:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./migrations/scripts/create_metadata_db.sql:/docker-entrypoint-initdb.d/01.sql
      - ./migrations/scripts/create_metadata_schema.sql:/docker-entrypoint-initdb.d/02.sql
      - ./migrations/scripts/install_ltree.sql:/docker-entrypoint-initdb.d/03.sql

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - "8750:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    logging:
      driver: none
    volumes:
      - ./local_config/pgadmin/:/var/lib/pgadmin/
    depends_on:
      - db

networks:
  default:
    external:
      name: pilot-network
