name: Run Docker Compose Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run-docker-compose-tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Init Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Poetry Version
        run: poetry version
      - name: Start Docker Compose
        run: |
          [ ! -f .env ] && touch .env
          [ -d local_config/pgadmin/sessions ] && sudo chmod 777 -R -f local_config/pgadmin/sessions
          sudo chmod 777 -R -f local_config/pgadmin/sessions
          docker-compose -f docker-compose.yaml down -v
          docker network create pilot-network
          docker-compose up -d
      - name: Get logs from Alembic container
        run: |
          docker logs --tail 1000 -f metadata_alembic_1
      - name: Run Tests Inside Compose
        run: |
          docker exec metadata_web_1 pip install --user poetry==1.1.12
          docker exec metadata_web_1 poetry config virtualenvs.in-project false
          docker exec metadata_web_1 poetry install --no-root --no-interaction
          docker exec metadata_web_1 poetry run pytest --verbose -c tests/pytest.ini
      - name: Tear Down Docker Compose
        run: docker-compose -f docker-compose.yaml down -v
